### ISSUE TITLE
Accessibility: Fill upvote / downvote icons

### ISSUE THREAD

**Issue by MrUltimate** [burhan-syed/troddit#10]
Hey, loving this! I've totally replaced reddit.com with this! 

One thing I'm noticing is that the site can use a few accessibility improvements (I'm a product design so forgive me, but I can't help but notice these things). As such, one of the most basic things anyone will do is upvote/downvote, relying solely on color to indicate that the button has been clicked is a major accessibility issue (consider color blind, or people hard of vision).

**Comment by burhan-syed** [comment]
Thanks for the suggestion. This is fixed with 9502fc5e29cd019040d1cb5cc23e24064fa6987a
