### ISSUE TITLE
[Feature Request] Edit Comment/Post feature?

### ISSUE THREAD

**Issue by LewsTherinTelescope** [burhan-syed/troddit#109]
Glad to find a web client that allows commenting, as that's the main thing that's kept me using the official site. However, as far as I can tell, there isn't a way to edit an existing comment or post. Am I just missing it? If not, are there plans to add this eventually?

**Comment by burhan-syed** [comment]
This is not currently implemented but it is planned with a refactor of the commenting system.
similar to #101

**Comment by LewsTherinTelescope** [comment]
Thanks! Got a 403 in the console whenever I tried to edit anything at first, but fixed that by logging out and back in—I assume it just didn't ask for the edit permission until now?

**Comment by burhan-syed** [comment]
Exactly. This required new "Edit" permissions which was not granted if you logged into troddit prior. This is called out briefly in the changelog.
