### ISSUE TITLE
Images in gallery are out of order

### ISSUE THREAD

**Issue by danshilm** [burhan-syed/troddit#11]
Example:

- Post on [troddit](https://www.troddit.com/r/okbuddyreiner/comments/tbypua/erens_paths_conversation_with_armin)
- Post on [reddit](https://www.reddit.com/r/okbuddyreiner/comments/tbypua/erens_paths_conversation_with_armin)

**Comment by ElijahPepe** [comment]
Seems to be [these lines](https://github.com/burhan-syed/troddit/blob/295657ea7ce339ebeb5b988d0aeb1292da0e9cb9/lib/utils.ts#L240-L259).

I observed that in the Network panel of Firefox's DevTools that the images are in fact being received in that order. I'll do some investigating to see why `post.media_metadata` is returning those posts in that order.

**Comment by ElijahPepe** [comment]
I've found a way to return the proper order using `post.gallery_data` and am submitting a pull request now.

**Comment by burhan-syed** [comment]
thanks, PR merged with 06e659d58fb18ed51a5897a6e65972a52fc240cd
