### ISSUE TITLE
Dedicated button to expand/collapse a comment

### ISSUE THREAD

**Issue by DWSuryo** [burhan-syed/troddit#147]
As far as I use it today, on comment section, when you click the comment area once, it instantly collapses/expand. It can be unfriendly to click something in comment section as every time you click or select the text, it changes behavior. Would be nice if there's a button to do that. Double clicking like in old reddit (RES) can be an option too but I don't really recommend that one.

**Comment by burhan-syed** [comment]
duplicate of #100   
find the Ribbon Collapse toggle for comments in the settings!

**Comment by DWSuryo** [comment]
Sorry, I haven't seen the option prior requesting. Thank you for the notice by the way.
