### ISSUE TITLE
Impact of Reddit new policy to troddit

### ISSUE THREAD

**Issue by dtantono** [burhan-syed/troddit#159]
Hi
Reddit announced new update API access and what is the impact of the troddit?
https://www.reddit.com/r/reddit/comments/12qwagm/an_update_regarding_reddits_api/

**Comment by burhan-syed** [comment]
I will need to keep an eye on this but as of now it is highly likely Reddit will require the usage of a premium API for third party apps like troddit to continue to function. It's not entirely clear how expensive this new API will but this will likely mean troddit will need to be crowdfunded or move to a premium subscription model. 

The developer of Apollo made a helpful post here for reference. 
[https://www.reddit.com/r/apolloapp/comments/12ram0f/had_a_few_calls_with_reddit_today_about_the/](https://www.reddit.com/r/apolloapp/comments/12ram0f/had_a_few_calls_with_reddit_today_about_the/)

**Comment by marcobarbierato** [comment]
> 50 million requests costs $12,000

https://www.troddit.com/r/apolloapp/comments/13ws4w3/had_a_call_with_reddit_to_discuss_pricing_bad

**Comment by blunderedbishop** [comment]
>50 million requests costs $12,000

https://www.reddit.com/r/apolloapp/comments/13ws4w3/had_a_call_with_reddit_to_discuss_pricing_bad

**Comment by burhan-syed** [comment]
Troddit.com has averaged just under 400,000 Reddit API requests for the past 3 days. 
That's 12,000,000 requests per month or about $3,000 a month with the proposed rate. 
Troddit.com is also averaging just under 1,000,000 reddit images/videos served per day so if that also counts towards API use the cost is easily 3-4 times higher. 

Needless to say I won't be able to support that. 

Troddit.com averages 4 to 5k unique users per day so a cheap $1 or $2 dollar subscription may be able to cover costs but this is difficult to predict as many users will likely leave and users who will pay will likely be power users and use more API requests so the actual cost may need to be 2-3x higher. 

With that being said, Reddit is going to continue to offer free tiers for their API: 
 - 100 queries per minute per OAuth client id
 - 10 queries per minute for no OAuth.  

So if you would want to continue to use troddit for free it is possible to setup your own local troddit instance and create an OAuth client id with Reddit for a fairly uninterrupted service. However, this hinges on Reddit keeping OAuth app creation easy and it's a possibility this would turn into a manually reviewed service.  

I'll be contemplating on whether to keep troddit.com running in a paid state. In either case I will keep this repository up and open.

**Comment by olivertzeng** [comment]
I started using troddit because I AM ANGRY

**Comment by burhan-syed** [comment]
updated post about the future of troddit here: 
[https://reddit.com/r/TrodditForReddit/comments/14745id/the_future_of_troddit](https://reddit.com/r/TrodditForReddit/comments/14745id/the_future_of_troddit)

**Comment by Joshndroid** [comment]
I self host troddit with my own api key on the docker container and as of right now my latest posts in my 'home' are 9 hours old... was today D Day for the reddit changes?

**Comment by dtantono** [comment]
@burhan-syed I suppose the google form have been terminated and you switch to troddit+ on the website for registration. May I know how long the membership approval process?

**Comment by burhan-syed** [comment]
@dtantono memberships are on hold indefinitely. That is all I can really say for now.

**Comment by dtantono** [comment]
@burhan-syed  Understood, I hope this project will not reach EOL as well. BTW, suppose the registration process is online once again. trodditcom will notify pending new user by email. is that so?

**Comment by Joshndroid** [comment]
I still use troddit with my own account self hosted and it's working as normal. Thanks for keeping it going

**Comment by dtantono** [comment]
@Joshndroid sorry I am quite amateur in docker setup. do you know how to reddit login with troddit?

**Comment by Joshndroid** [comment]
You will need to run the docker image while parsing the environment variables that are listed on the home page - https://github.com/burhan-syed/troddit

keep in mind you will need to create an app key with the old.reddit link as advised below the environment variables bit

I use unraid as my serverOS and i created a troddit template and shared it with the unraid community that makes it a little easier but there is still a slight but of setup
