### ISSUE TITLE
Link to poll incorrect

### ISSUE THREAD

**Issue by arafatamim** [burhan-syed/troddit#16]
For example: https://www.troddit.com/r/poll/comments/sc069x/what_month_is_your_birthday.
The `View poll` link points to https://troddit.com/poll/sc069x instead of https://reddit.com/poll/sc069x

**Comment by burhan-syed** [comment]
Thanks, these will direct back to Reddit since there are no API points to submit poll responses. 
May implement a view only for the poll in the future. 

2f6c0edf6042e0bb81d49f606a8d38a6594f3ee6
