### ISSUE TITLE
ETP Popup shows up repeatably with ETP disabled

### ISSUE THREAD

**Issue by Saeraphinx** [burhan-syed/troddit#165]
This little popup on the bottom of the screen pops up every 10-30 seconds after scrolling for about 5 minutes through a subreddit with videos and pictures. I have ETP turned off.
This seems to be repeatable. Have no clear idea what error its referencing, but loading appears to stop after scrolling a few pages worth more.

![image](https://github.com/burhan-syed/troddit/assets/37343661/e39a249f-6360-40ed-b7d8-f138e673045e)

**Comment by burhan-syed** [comment]
This will happen if a rate limit is reached, there is some internal error getting media files for a post, or if Reddit can't be reached for whatever reason. 
For now I've suppressed this error if there is a subsequent successful render to the feed. 
If this continues to happen for you let me know what subreddit/feed is causing this issue.
