### ISSUE TITLE
Docker image ENV variables

### ISSUE THREAD

**Issue by SakethKanchi** [burhan-syed/troddit#183]
How do i add ENV variables to docker image/container. I installed the troddit using Docker Deploy method: 
```
docker pull bsyed/troddit
docker run -d --name troddit -p 3000:3000 bsyed/troddit
```
Now how do i add env variables and sign in with my account?

**Comment by burhan-syed** [comment]
Please see docker documentation. You can use the [-e, --env](https://docs.docker.com/reference/cli/docker/container/run/#env) options or supply a file with `--env-file`
