### ISSUE TITLE
How to deploy troddit with docker?

### ISSUE THREAD

**Issue by cinetube** [burhan-syed/troddit#2]
How to deploy troddit with docker?

**Comment by somedevreally** [comment]
docker support, yes please :)

**Comment by danmed** [comment]
Yes please!

**Comment by firestrife23** [comment]
Yes

**Comment by tillcash** [comment]
provide docker for arm

**Comment by Joshndroid** [comment]
Yes docker support plz

**Comment by burhan-syed** [comment]
See updated Readme for how to create a Docker image.

**Comment by Joshndroid** [comment]
> See updated Readme for how to create a Docker image. 

Thanks for the new readme docker instructions
Are you also looking at publishing an image up on places like dockerhub or quay?
I run unraid on my 'server pc' and would like to generate a template for it but need a docker repo such as dockerhub..

**Comment by burhan-syed** [comment]
> Are you also looking at publishing an image up on places like dockerhub or quay?

You'll find the dockerhub image here: https://hub.docker.com/r/bsyed/troddit

**Comment by Joshndroid** [comment]
> > Are you also looking at publishing an image up on places like dockerhub or quay?
> 
> You'll find the dockerhub image here: https://hub.docker.com/r/bsyed/troddit

Perfect thanks mate

**Comment by cinetube** [comment]
@burhan-syed Thanks for providing docker support.
