### ISSUE TITLE
Feature request - Add option to hide/unhide posts

### ISSUE THREAD

**Issue by mohandeblaze** [burhan-syed/troddit#21]
Similar to save/unsave posts, this option will allow us to hide/unhide the already read posts to not appear again the feed, to avoid too much scrolling to find new posts.

**Comment by burhan-syed** [comment]
Thanks for the suggestion!

Locally tracking read posts with 048827d9496d47a056cb85cf332272ad7f7dd9db. Also includes read post filter. 
Additionally added support for Reddit's "hide"/"unhide" post feature with 5f98c408747dd75b236ebc089e0dd39772e4f567. 

Posts are marked as read manually or automatically when opened. Option to mark posts as read when scrolled past still WIP.
Posts can be hidden in the post overflow menu or with the hide option in classic row view.

**Comment by mohandeblaze** [comment]
Thanks! This was one feature I missed in the app and now it truly replaces the laggy official website for me.
