### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by cinetube** [burhan-syed/troddit#4]
Personally I liked Troddit more than Libreddit. I would like to see the following features to be implemented on Troddit. 

1. Need docker image immediately to deploy it easily. 
2. Need a local account option to save subscribed sub-reddits and Troddit will display posts only from subscribed sub-reddits. I don't want to login reddit.

**Comment by burhan-syed** [comment]
1. Tracking this in issue #2 
2. If you're not logged in you can now locally subscribe to a subreddit by navigating to the subreddit and hitting the '+' in the sub dropdown: 
![image](https://user-images.githubusercontent.com/32972409/146658343-1072e295-07da-4dfe-9b25-78dce7306e57.png)

Locally subscribed to subreddits will appear below in the 'local subs' selection. Navigating to 'Home' or '/' with local subreddits will only display posts from those subs. You can locally unsubscribe by navigating to the subreddit and hitting '-' where the '+' was.
