### ISSUE TITLE
Bad scrolling on many android devices including Oneplus 8

### ISSUE THREAD

**Issue by gsingh704** [burhan-syed/troddit#64]
My oneplus 8 wirks well for all the website except this. While scrolling it stutters and more so in comments

**Comment by gsingh704** [comment]
Only happen on webview based(soul browser) and chromium based browsers(brave , kiwi). On firefox it work well

**Comment by burhan-syed** [comment]
Chrome has poor performance scrolling complex SVGs. These have been hidden behind a button for voting on small devices.
