### ISSUE TITLE
Feature request - Pagination and Local account

### ISSUE THREAD

**Issue by cinetube** [burhan-syed/troddit#7]
I am requesting 2 new features. 

1. Enable Pagination - So that the user can set the number of maximum post per page.  (e.g. 20, 30, 40)

2. Local Account - All the locally subscribed reddit should be stored in a local account from which the subreddits list can be exported in OMPL format. There should be a feature to import the OMPL file containing the list of subreddits.

**Comment by burhan-syed** [comment]
For local accounts: Currently you can join subreddits locally without logging in although these are not stored behind a password protected account. They are stored locally in your browser's storage and will persist as long as you don't clear your browser's cookies and site data. 

For now if you follow subreddits on Reddit you can import them locally to troddit by navigating to [https://www.reddit.com/subreddits](https://www.reddit.com/subreddits), clicking on the multireddit of your subscriptions, then replacing 'reddit' with 'troddit' in the URL. Finally, clicking on 'Join All' in the dropdown menu next to the 'Join' button will subscribe you to all of your subs locally. 

I haven't built an easy to way to import/export this but it can be done by editing/copying the key-value pair in the site's local storage. For local subs the key is "localSubs" then subs are stored in a simple array: ["subname1","subname2"].
