### ISSUE TITLE
Add option to collapse/hide link preview images in card/media views

### ISSUE THREAD

**Issue by mbestavros** [burhan-syed/troddit#76]
Feature request: As is, link posts display the preview image for the link at the same size as direct image posts. While the preview can be helpful to see, it's almost never necessary for it to be a full-size image, and I personally think it ends up being a waste of space most of the time. The standard Reddit web client does not show link preview images at all.

It would be nice to have an option to either collapse the link previews or hide them entirely in the card views (without needing to resort to the "classic rows" style).

**Comment by burhan-syed** [comment]
changed with 40552f49e8252c7fb8411dfab75489d03b0f7e36

**Comment by mbestavros** [comment]
@burhan-syed Thank you! This implementation is lovely! Exactly what I had in mind 😄
