### ISSUE TITLE
Horizontal Scroll on troddit.com/best

### ISSUE THREAD

**Issue by EthanChau1999** [burhan-syed/troddit#77]
Hello, on troddit.com the page loads nicely and there is no horizontal scroll:
![image](https://user-images.githubusercontent.com/109206151/178679095-162df761-c832-4f2b-9a73-004733ca6353.png)

But on different sort options (e.g. best, new, top, hot) the page seems to load slightly too wide, so a horizontal scroll bar is added at the bottom:
![image](https://user-images.githubusercontent.com/109206151/178679428-4fac00ce-af5c-4f73-82ff-0a5815538bc1.png)

Clicking on posts and viewing subreddits does not cause this issue (e.g. troddit.com/r/formula1/best), it only happens on troddit.com/best, troddit.com/hot, troddit.com/rising, etc. 

I am on chrome version 103.0.5060.114 (Official Build) (64-bit)

**Comment by burhan-syed** [comment]
@EthanChau1999 I wasn't able to reproduce this but pushed out a change to address the issue. Lmk if you still see this.
