### ISSUE TITLE
.env.local

### ISSUE THREAD

**Issue by Uproar7425** [burhan-syed/troddit#79]
Where do I have to put the .env.local when running troddit in docker, I get "server error" when trying to login.

**Comment by Uproar7425** [comment]
I got it, put

```environment:
      - CLIENT_ID=1xLytUctn2fmLjX34tcXyw
      - CLIENT_SECRET=s4XNoSdnRxFQ4bGY0YZOcW9HlybJOw
      - REDDIT_REDIRECT=http://localhost:3000/api/auth/callback/reddit
      - NEXTAUTH_SECRET=qKgyBxjKPmN07Jp69iMw7KY8TMzV4pU2hLqDtGExbck=
      - NEXTAUTH_URL=http://localhost:3000/
```

in the dockerfile.

**Comment by burhan-syed** [comment]
@Uproar7425 if you haven't already you'll want to delete your Reddit app and make a new one since you shared the ID and secret here..
