### ISSUE TITLE
[Reddit Login] Invalid Client ID

### ISSUE THREAD

**Issue by Joshndroid** [burhan-syed/troddit#8]
I have been trying to login to reddit to be able to have a bit more functionality.

I keep getting the error page
```

bad request (reddit.com)

you sent an invalid request
— invalid client id.
```
I have tried desktop firefox, mobile firefox, mobile bromite

**Comment by burhan-syed** [comment]
Is this in the main hosted instance (troddit.com) or your own instance? If it is the latter please see the ReadMe section on setting environment variables.

**Comment by Joshndroid** [comment]
Sigh... i fixed up the client ID section and am back... Cheers :)
