### ISSUE TITLE
Navigation\scroll bug

### ISSUE THREAD

**Issue by Vozf** [burhan-syed/troddit#85]
I quite often get the bug with the scroll when my scroll position changes without any actions and the posts I used to have on my screen go a couple of scroll below or above my new position. Have no idea how to reproduce it but I've encountered this bug almost every day for the past couple of weeks

**Comment by burhan-syed** [comment]
As a temporary solution turning off the 'monitor feed' and 'check on focus' settings will prevent this behavior.  
I've introduced some changes that should limit this occurrence but will need to monitor it.

**Comment by jaimehrubiks** [comment]
I disabled check on focus, monitor feed and monitor comments, and still, every time no exception that I lock and unlock my phone back, troddit reloads the page, and scroll back is reset back to the top post above the comments

**Comment by Vozf** [comment]
Disabling montior feed and check on focus fixed the issue for me on pc
