### ISSUE TITLE
Give option to not load tweets.

### ISSUE THREAD

**Issue by gsingh704** [burhan-syed/troddit#9]
Sometime the  tweets load later and move the page as they load which i don't like. Other option can be to make them same length box and load the same height box , so that the content don't move.

**Comment by burhan-syed** [comment]
Tweets are replaced with a placeholder to prevent layout shift in multi-column modes. Opening a post will or browsing in single column mode will render the twitter embed with a placeholder before it's fully loaded in. 

c7d4304349629acbe36384b6f5ce5196d644cc0d
